title: R26e Documentation
description: R26e Documentation
baseurl: "/fsae-r26e"
url: "https://brianstm.github.io"

# Remote theme options
remote_theme: pages-themes/cayman@v0.2.0

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    preview: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
