title: R26e Documentation
description: R26e Documentation
baseurl: "" 
url: "https://brianstm.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock