title: R26e Documentation
description: R26e Documentation
baseurl: "/ghp"
url: "https://brianstm.github.io"

# Remote theme options
remote_theme: pages-themes/cayman@v0.2.0

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
